version: '3'
services:
  frpc:
    image: fatedier/frpc:v0.51.3
    container_name: frpc
    restart: always
    volumes:
      - /root/frpc/frpc.ini:/etc/frp/frpc.ini
    network_mode: host
    command: ["-c", "/etc/frp/frpc.ini"]
